apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2-sample-app-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: co2-sample-app
        image: vrukshali26/sample:v1
        ports:
        - containerPort: 4444

